# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Uninstall app"
  lane :uninstall_app do |options|
    package = options[:package]
    adb(command: "uninstall #{package}")
  end

  desc "Change app name"
  lane :change_app_name do |options|
    name = options[:newname]
    android_change_app_name(newName: name)
  end

  desc "Change app package name"
  lane :change_package_app_name do |options|
    packageName = options[:package]
    # sh("dart run rename --bundleId #{packageName}")
    current_directory = Dir.pwd
    parent_directory = File.expand_path("..", current_directory)
    android_change_package_identifier(newIdentifier: packageName)
    android_change_package_identifier(newIdentifier: packageName, manifest: "#{parent_directory}/app/src/debug/AndroidManifest.xml")
    android_change_package_identifier(newIdentifier: packageName, manifest: "#{parent_directory}/app/src/profile/AndroidManifest.xml")
    sh("sed -i '1s/.*/package #{packageName}/' #{parent_directory}/app/src/main/kotlin/com/example/album_cover_craft/MainActivity.kt")
    android_update_package_identifier(gradleFilePath: "#{parent_directory}/app/build.gradle", newIdentifier: "#{packageName}")
  end

  desc "Configure firebase"
  lane :configure_firebase do
    sh()
  end
  
end
